version: "3"

dotenv: [".env"]
silent: true

tasks:
  app:
    cmds:
      - turbo run dev --scope="launchpad-webapp"

  faucet:
    cmds:
      - turbo run dev --scope="launchpad-faucet"

  indexer:
    cmds:
      - turbo run dev --scope="launchpad-indexer"

  indexer-docker:
    cmds:
      - docker build --no-cache -t launchpad-indexer -f apps/indexer/Dockerfile .
      - docker run -p 8080:8080 --env-file ./apps/indexer/.env launchpad-indexer

  build-image-webapp:
    cmds:
      - docker-compose build app

  run-container-webapp:
    cmds:
      - docker-compose up -d app

  stop-container-webapp:
    cmds:
      - docker-compose down

  build-and-run-webapp:
    deps: [build-image-webapp]
    cmds:
      - task run-container-webapp
    preconditions:
      - task: stop-container-webapp
        silent: true
        ignore_error: true